### ISSUE TITLE
Determine a name for this library.

### ISSUE THREAD

**Issue by kberryUSGS** [USGS-Astrogeology/SpiceRefactor#11]
Moving my comment from the closed PR:

The new library's name is currently set as `usgsephem`. 

I'm sure this is intended as a preliminary name and I don't have any alternative suggestions, but, 
if someone said to me "here is an ephemeris software library from the usgs" I would expect to be able to use it to look up the position of an astronomical body, given a time. To be more explicit, I would expect to be able to do something like `usgsephem.getCoord('Mars', 2018-01-01:01:01:01, 'J2000')` This is not how I currently understand the purpose of this software library. Are we planning to do this and provide default ephemerides to use (de430, etc) ?

**Comment by jessemapel** [comment]
It's largely just a placeholder name I came up with in about 30 seconds. We need to find a better name.

**Comment by kberryUSGS** [comment]
@jessemapel :+1: I'll leave this ticket here as a "come up with a better name" ticket.

**Comment by jessemapel** [comment]
W.A.I.T. Where Am I aT

**Comment by jessemapel** [comment]
Arceus

**Comment by jessemapel** [comment]
E.A.L. Ephemeris Abstraction Library
